### ISSUE TITLE
v1.3.0 has a breaking change

### ISSUE THREAD

**Issue by ljharb** [wavded/babel-tape-runner#11]
If you check out https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb - and bump `babel-tape-runner` from `v1.2` to `v1.3`, you'll see that `npm test` fails.

This is a breaking change in a minor version. We can't upgrade to v2.0 because we're on babel 5 (babel 6 is too buggy for us to use just yet).

Is there any way you could release a `v1.3.1` that doesn't break our repo?

**Comment by wavded** [comment]
Sorry about that @ljharb, I pushed 1.3.1 and deprecated 1.3.0.  Babel 6 people should use 2.0.0.

**Comment by ljharb** [comment]
Thank you!
