### ISSUE TITLE
Using babel-tape-runner with Isomorphic/Universal React Components 

### ISSUE THREAD

**Issue by veeracs** [wavded/babel-tape-runner#13]
Running into an issue running tests on Universal React Components that import static assets like,

```
import 'Toggle.scss';
```

Could not run my tests if my React components have references to static assets.

**Comment by Wilfred** [comment]
FWIW, we worked around this with:

``` js
if (process.env.NODE_ENV == "production" || process.env.NODE_ENV == "dev") {
  // We can't load CSS in tests in the native node environment.
  require('./Whatever.css');
}
```

**Comment by veeracs** [comment]
Thanks @Wilfred!

I've been using...

```
if (!global.__TESTING__) {
  require('./Logo.scss');
}
```

Where we set below when running tests..

```
global.__TESTING__ = true
```
