### ISSUE TITLE
compare with `tape -r babel-register`

### ISSUE THREAD

**Issue by fibo** [wavded/babel-tape-runner#17]
Hi,

I read on tape docs that it is possible to do

```
tape -r babel-register test.js
```

How this compares with the use of _babel-tape-runner_? Is it the same?

**Comment by wavded** [comment]
@fibo I haven't taken a good look yet but I think it is, therefore making this library not necessary anymore.  If it works for you, I'd go that route if it were me.

**Comment by fibo** [comment]
I found babel-tape-runner really useful, at first. Then I not noticed that tape feature, which works for me. Maybe it was added to tape documentation later.

**Comment by wavded** [comment]
Yeah, the feature was added after this project was started.
