### ISSUE TITLE
What is the difference with simply using `babel-node`?

### ISSUE THREAD

**Issue by ghost** [wavded/babel-tape-runner#2]
What is the difference and why do I need this module? 

> ref: https://github.com/bucaran/generator-rise/pull/11/files 

Thanks.

**Comment by brigand** [comment]
It supports globs

**Comment by ghost** [comment]
Thanks. :+1: 

Now, I understand this module breaks Spartan coverage. Any ideas?

Please see https://github.com/bucaran/generator-rise/issues/10

**Comment by wavded** [comment]
This appears to be addressed, closing for now, if not, feel free to comment.
