### ISSUE TITLE
How to ignore style imports?

### ISSUE THREAD

**Issue by kevzettler** [wavded/babel-tape-runner#24]
I have `import "../styles.scss"` statements in some client code. Trying to test this in node environment throws errors

```
> music-store@1.0.1 test /Users/kev/code/
> babel-tape-runner tests/**/*.js

/Users/kev/code/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/kev/code/styles.scss: Unexpected token, expected ; (1:11)
> 1 | body, html {
    |            ^
  2 |   padding: 0px;
  3 |   margin: 0px;
  4 |   height: 100%;
```

**Comment by wavded** [comment]
First thought was to conditionally include those, e.g.

```js
if (process.env.NODE_ENV !== 'test') require('../styles.scss')
```

But perhaps there are other ways that work better, haven't run into this issue personally so shooting from the hip.

**Comment by kevzettler** [comment]
That is a viable option but it will be a large effort to scale. If a project is liberally using style sheet imports it will take much manual instrumentation and leads to plenty of opportunities for future stylesheet additions to forget the environment guard.

**Comment by wavded** [comment]
This or something like it may help: https://github.com/morlay/babel-plugin-transform-require-ignore

**Comment by brigand** [comment]
You could use a babel plugin that strips them when `NODE_ENV=test`. [Example](http://astexplorer.net/#/gist/9b757de253a80abc72d110deefe327c1/1a21ffa7e0210bc276f27630a6cdbe8736a4bb8a).

**Comment by kevzettler** [comment]
Closing issue because the solutions provided are sufficient.
