### ISSUE TITLE
how to invoke polyfill?

### ISSUE THREAD

**Issue by djMax** [wavded/babel-tape-runner#7]
I'm using async/await and thus need the polyfill. Can babel-tape-runner add that somehow?

**Comment by brigand** [comment]
I think you can do `import 'babel-polyfill'` to get the polyfill (install it first, of course).

Docs: https://babeljs.io/docs/usage/polyfill/

**Comment by djMax** [comment]
Sure, but the problem is now I have to do that in every test file because I don't know which will run first. Essentially I want an option to the runner that will either import the polyfill or import some file I make that imports the polyfill. I need a "before all" type of thing

**Comment by wavded** [comment]
I haven't migrated to babel-core 6 yet, I'm guessing it doesn't include the polyfill anymore?  seems like that should be provided in `babel-tape-runner` to match the existing functionality, or do people disagree?  can you specify to use the polyfill in your `.babelrc` ?

**Comment by djMax** [comment]
I'm just migrating myself, so I may be getting this wrong, but it seems you have to include the polyfill at runtime and not in the babelrc.

**Comment by aaronshaf** [comment]
+1

**Comment by wavded** [comment]
`2.0.0` now includes the polyfill
